 Let's delve deeper into the use of the * operator for handling arbitrary argument lists in Python functions.
Arbitrary Argument Lists (*args)

In Python, you can define functions that accept a variable number of arguments using *args. This is useful when you want to pass an unspecified number of arguments to a function. Here’s how it works:

In [2]:
def sum_values(*args):
    total = 0
    for num in args:
        total += num
    return total

result1 = sum_values(1, 2, 3, 4)  # Passing 4 arguments
result2 = sum_values(10, 20, 30)  # Passing 3 arguments

print(result1)  # Output: 10 (1 + 2 + 3 + 4)
print(result2)  # Output: 60 (10 + 20 + 30)

10
60


 In Python, the ** (double asterisk) operator is used for dictionary unpacking and keyword arguments in function definitions. Let's explore each of these uses in detail:
Dictionary Unpacking (**kwargs)

In Python, you can use ** to unpack dictionaries into keyword arguments in function calls. This is useful when you have a dictionary of key-value pairs and you want to pass them as keyword arguments to a function.

In [1]:
def print_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

# Example usage:
print_info(name="Alice", age=30, city="New York")


name: Alice
age: 30
city: New York


**kwargs allows flexibility in the number of keyword arguments a function can accept.
It captures all additional keyword arguments passed to the function as a dictionary.
You can combine **kwargs with normal positional and keyword arguments, but **kwargs must come after all other arguments in the function signature.

In a function definition, *args must appear before **kwargs.
This ordering ensures that Python correctly assigns positional arguments to args and keyword arguments to kwargs.

In [3]:
def example_function(a, b, *args, **kwargs):
    print(f"a = {a}")
    print(f"b = {b}")
    
    print("\nAdditional positional arguments (*args):")
    for arg in args:
        print(arg)
    
    print("\nAdditional keyword arguments (**kwargs):")
    for key, value in kwargs.items():
        print(f"{key} = {value}")

# Example usage:
example_function(1, 2, 3, 4, name='Alice', age=30)


a = 1
b = 2

Additional positional arguments (*args):
3
4

Additional keyword arguments (**kwargs):
name = Alice
age = 30


Let's create a simple example that uses zip, the unpacking operator (*), and list comprehension. We'll combine two lists into a list of tuples, transpose the combined list, and then process the transposed data using list comprehension.
Example Scenario

We have two lists: one with names and one with ages. We want to:

    Pair each name with its corresponding age using zip.
    Transpose the paired list using the unpacking operator (*).
    Use list comprehension to create a new list that contains a formatted string for each name and age.

In [16]:
# Two lists: names and ages
names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 35]

# Step 1: Pair each name with its corresponding age using zip
paired_list = list(zip(names, ages))
print("Paired List:", paired_list)

# Step 2: Transpose the paired list using the unpacking operator (*)
transposed_list = list(zip(*paired_list))
print("Transposed List:", transposed_list)

# Step 3: Use list comprehension to create a new list with formatted strings
formatted_list = [f"{name} is {age} years old" for name, age in paired_list]
print("Formatted List:", formatted_list)


Paired List: [('Alice', 25), ('Bob', 30), ('Charlie', 35)]
Transposed List: [('Alice', 'Bob', 'Charlie'), (25, 30, 35)]
Formatted List: ['Alice is 25 years old', 'Bob is 30 years old', 'Charlie is 35 years old']


torch.repeat_interleave(input, repeats, dim=None, *, output_size=None) → Tensor
Parameters
input (Tensor) – the input tensor.

repeats (Tensor or int) – The number of repetitions for each element. repeats is broadcasted to fit the shape of the given axis.

dim (int, optional) – The dimension along which to repeat values. By default, use the flattened input array, and return a flat output array.

Keyword Arguments
output_size (int, optional) – Total output size for the given axis ( e.g. sum of repeats). If given, it will avoid stream synchronization needed to calculate output shape of the tensor.

In [19]:
import torch
x = torch.tensor([1, 2, 3])
x.repeat_interleave(2)
y = torch.tensor([[1, 2], [3, 4]])
print(torch.repeat_interleave(y, 2)) # without dim, it flattens array
print(torch.repeat_interleave(y, 3, dim=1))
print(torch.repeat_interleave(y, torch.tensor([1, 2]), dim=0))
torch.repeat_interleave(y, torch.tensor([1, 2]), dim=0, output_size=3)

tensor([1, 1, 2, 2, 3, 3, 4, 4])
tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]])
tensor([[1, 2],
        [3, 4],
        [3, 4]])


tensor([[1, 2],
        [3, 4],
        [3, 4]])

In Python, a leading underscore in front of a function name (or any identifier) serves as a naming convention to indicate that the function is intended for internal use only. This is a common practice to signal to developers that the function is part of the internal implementation of a class or module and is not meant to be used directly by users of the class or module.
Key Points about Leading Underscores

    Single Leading Underscore (_name):
        By convention, a single leading underscore indicates that the function or variable is intended for internal use.
        It is a weak "internal use" indicator, meaning it is still accessible from outside the module or class but should be used with caution.

    Double Leading Underscore (__name):
        A double leading underscore triggers name mangling, which means the interpreter changes the name of the variable or function to include the class name. This helps prevent name collisions in subclasses.
        For example, __my_var in class MyClass becomes _MyClass__my_var.

    Single Trailing Underscore (name_):
        This is used to avoid conflicts with Python keywords or built-in functions.
        For example, class_ could be used to avoid a conflict with the class keyword.
OR
        The underscore _ at the end of normal_ indicates that this method operates in-place, meaning it modifies the tensor (self.weight) directly.

    Double Leading and Trailing Underscore (name):
        These are reserved for special use in the language. Such names are referred to as "magic" or "dunder" methods and have special meaning, such as __init__ for initializers or __str__ for string representation.

In [ ]:
class MyClass:
    def __init__(self):
        self._internal_state = 0

    def _increment_internal_state(self):
        self._internal_state += 1

    def public_method(self):
        self._increment_internal_state()
        return self._internal_state

# Using the class
my_instance = MyClass()
print(my_instance.public_method())  # 1
print(my_instance.public_method())  # 2

# Trying to access internal method directly
my_instance._increment_internal_state()  # It's accessible but should be avoided
print(my_instance._internal_state)  # 3
